on:
  workflow_dispatch: {}

name: Semgrep
jobs:
  buildGradleLockfile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build lockfile
      run: gradle dependencies --write-locks 
    - name: Upload lockfile Artifact     
      uses: actions/upload-artifact@v3
      with:
        name: gradlelockfile
        path: gradle.lockfile
  semgrep:
    needs: buildGradleLockfile
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from previous job
      uses: actions/download-artifact@v3
      with:
        name: gradlelockfile
    - run: semgrep ci 

