on:
  workflow_dispatch: {}

name: Semgrep
jobs:
  buildGradleLockfile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build lockfile
      # run: gradle dependencies --write-locks 
      run: gradle resolveAndLockAll --write-locks
      #--no-configuration-cache --info --stacktrace --no-parallel
    - name: Upload lockfile Artifact     
      uses: actions/upload-artifact@v4
      # with:
      #   name: gradlelockfile
      #   path: /home/runner/**/*.lockfile
      with:
        name: gradlelockfile
        path: gradle.lockfile
  semgrep:
    needs: buildGradleLockfile
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from previous job
      uses: actions/download-artifact@v4
      with:
        name: gradlelockfile
    - run: semgrep ci --supply-chain

